CREATE TABLE STAFF (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  AGE INT NOT NULL
);

CREATE TABLE DEPARTMENT (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  DEPARTMENT_NAME VARCHAR(50) NOT NULL,
  DISTRICT_NAME VARCHAR(50) NOT NULL
);
