INSERT INTO %s.DEPARTMENTS (DEPARTMENT_NAME, DISTRICT_NAME) VALUES ('%s', '%s');
INSERT INTO %s.STAFF (ID, NAME, AGE) VALUES (%s, '%s', %s);
INSERT INTO %s.EMPLOYEES (FK_STAFF_ID, FK_DEPARTMENT_ID) VALUES (%s, %s);