SELECT D.DEPARTMENT_NAME, COUNT(S.NAME) FROM %1$s.DEPARTMENTS D
  JOIN %1$s.EMPLOYEES E ON D.ID = E.FK_DEPARTMENT_ID
  JOIN %1$s.STAFF S ON E.FK_STAFF_ID = S.ID
    WHERE S.AGE > ?
    AND S.AGE < ?
    AND D.DISTRICT_NAME = ?
      GROUP BY D.DEPARTMENT_NAME